version: "3"

services:
  server1:
    build: .
    ports:
      - "8080:8080"
    container_name: node1-container
    environment:
      - HOST=172.20.0.2
      - PORT=8080
      - MAX_NODE=4
      - SERVER_NAME=1
    networks:
      app_net:
        ipv4_address: 172.20.0.2
    command: python server.py

  server2:
    build: .
    ports:
      - "8081:8080"
    container_name: node2-container
    environment:
      - HOST=172.20.0.3
      - PORT=8080
      - MAX_NODE=4
      - SERVER_NAME=2
    networks:
      app_net:
        ipv4_address: 172.20.0.3
    command: python server.py

  server3:
    build: .
    ports:
      - "8082:8080"
    container_name: node3-container
    environment:
      - HOST=172.20.0.4
      - PORT=8080
      - MAX_NODE=4
      - SERVER_NAME=3
    networks:
      app_net:
        ipv4_address: 172.20.0.4
    command: python server.py

  server4:
    build: .
    ports:
      - "8083:8080"
    container_name: node4-container
    environment:
      - HOST=172.20.0.5
      - PORT=8080
      - MAX_NODE=4
      - SERVER_NAME=4
    networks:
      app_net:
        ipv4_address: 172.20.0.5
    command: python server.py

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
